import pandas as pd
df = pd.read_csv('data/VMAI_TABULAR_Data.csv')
print('Shape:', df.shape)
print()
print('=== Head (first 6) ===')
print(df.head(6).to_string())
print()
print('=== Describe ===')
print(df.describe().to_string())
print()
print('=== Category distribution ===')
print(df['category'].value_counts().to_string())
print()
print('=== Location distribution ===')
c = df['location'].value_counts()
for k, v in c.items():
    print(f'  {k}: {v}')
print()
nf = df['negation_flag'].mean()
hf = df['hedge_flag'].mean()
dl = (df['time_difference'] != -1).mean()
print(f'negation_flag mean: {nf:.3f}')
print(f'hedge_flag mean:    {hf:.3f}')
print(f'has deadline rate:  {dl:.3f}')
print()
z = (df['real_duration'] == 0).sum()
print(f'real_duration == 0: {z}')
nz = df[df['real_duration'] > 0]['real_duration']
print(f'real_duration > 0:  min={nz.min():.1f} max={nz.max():.1f} mean={nz.mean():.1f}')
print()
td = df[df['time_difference'] != -1]['time_difference']
print(f'time_difference (non -1): min={td.min():.1f} max={td.max():.1f} mean={td.mean():.1f}')
print()
print('=== Category vs real_duration mean ===')
print(df.groupby('category')['real_duration'].mean().to_string())
print()
print('=== Location vs real_duration mean ===')
print(df.groupby('location')['real_duration'].mean().to_string())
