"""add category_id to category_statistics

Revision ID: 2667094139c9
Revises: b1deeeceae45
Create Date: 2026-04-19 13:18:57.814595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2667094139c9'
down_revision: Union[str, Sequence[str], None] = 'b1deeeceae45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category_statistics', sa.Column('category_id', sa.UUID(), nullable=False))
    op.alter_column('category_statistics', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(op.f('category_statistics_category_name_key'), 'category_statistics', type_='unique')
    op.create_unique_constraint(None, 'category_statistics', ['category_id'])
    op.create_foreign_key(None, 'category_statistics', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('category_statistics', 'category_name')
    op.alter_column('category_statistics_locations', 'statistics_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category_statistics_locations', 'statistics_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.add_column('category_statistics', sa.Column('category_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'category_statistics', type_='foreignkey')
    op.drop_constraint(None, 'category_statistics', type_='unique')
    op.create_unique_constraint(op.f('category_statistics_category_name_key'), 'category_statistics', ['category_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('category_statistics', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('category_statistics', 'category_id')
    # ### end Alembic commands ###
